<AddBookDialog>
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height: "100dp"
    pos_hint:{'top':1}
    MDTextField:
        id: new_name_of_book
        hint_text: "Name"
        helper_text: "There will always be a mistake"
        helper_text_mode: "on_error"

    BoxLayout:
        id: bottom_nav
        size_hint: 0.3,0.8
        orientation: "horizontal"
        pos_hint: {'bottom':1,'center_x':0.5}
