
<MenuElement>:
    canvas.before:
        Color:
            rgba: hex(app.bg_screens_whitly_color)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [2,2]

    halign:"center"
    theme_text_color: "Custom"
    text_color: hex(app.icon_but_colors)


<CustomMenu>:
    position:"bottom"
    ver_growth:"up"
    hor_growth:"right"
    max_height: "150sp"
